# Generated by Django 3.0.7 on 2020-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canning_date',
            field=models.DateTimeField(default='2020-01-01 01:01', verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='compost_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_of_harvest',
            field=models.DateTimeField(default='2020-01-01 01:01', verbose_name='date_of_harvest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='destrbutor_humidity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='destrbutor_temp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='distrabuterID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='entry_market_date',
            field=models.DateTimeField(default='2020-01-01 01:01', verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='entry_store_date',
            field=models.DateTimeField(default='2020-01-01 01:01', verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='factoryID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='factory_humidity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='factory_temp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='farm_humidity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='farm_location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='farm_temp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='farmerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='market_humidity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='market_temp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='marktingID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_date',
            field=models.DateTimeField(default='2020-01-01 01:01', verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seed_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unite_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
